# Generated by Django 3.1.6 on 2021-04-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Comment',
            field=models.TextField(default=''),
        ),
    ]
