# Generated by Django 3.1.6 on 2021-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20210505_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='detail',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='Basic_Qualification',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='JOB_ID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
