# Generated by Django 3.1.6 on 2021-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_jobposting_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to=None)),
            ],
        ),
    ]
