# Generated by Django 3.1.6 on 2021-05-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pdf',
            field=models.FileField(upload_to='media'),
        ),
    ]
